server:
  port: 10010
spring:
  application:
    name: mystore-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
zuul:
  prefix: /api
  routes:
    item-service: /item/**
    search-service: /search/**
    user-service: /user/**
    auth-service: /auth/**
  add-host-header: true
  sensitive-headers: # 不过滤响应头里的敏感字段
mystore:
  jwt:
    pubKeyPath: E:\\MyTest\\rsa\\rsa.pub # 公钥地址
    cookieName: MYSTORE_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item
