server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql:///mystore
    username: root
    password: 123
    hikari:
      max-lifetime: 28830000
      maximum-pool-size: 9
  rabbitmq:
    host: 192.168.138.129
    username: mystore
    password: mystore
    virtual-host: /mystore
    template:
      exchange: mystore.item.exchange
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20

