server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql:///mystore
    username: root
    password: 123
  redis:
    host: 192.168.138.129
  rabbitmq:
    host: 192.168.138.129
    virtual-host: /mystore
    username: mystore
    password: mystore
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
mybatis:
  type-aliases-package: cn.lh.user.pojo